# ------------------------------------------------------------------------------
# Project: Aetherion
# Copyright (c) 2025-2026, Onur Tuncer, PhD, Istanbul Technical University
#
# SPDX-License-Identifier: MIT
# License-Filename: LICENSE
# ------------------------------------------------------------------------------

if(BUILD_DOCS)
    return()
endif()

# ------------------------------------------------------------------------------
# CppAD
#   Windows -> prebuilt vendor binaries (vendor/cppad/x64-{Debug,Release})
#   Linux   -> FetchContent build from source
# ------------------------------------------------------------------------------
if(WIN32)
    set(CPPAD_VENDOR_ROOT "${CMAKE_SOURCE_DIR}/vendor/cppad")

    add_library(CppAD::cppad STATIC IMPORTED GLOBAL)
    set_target_properties(CppAD::cppad PROPERTIES
        IMPORTED_CONFIGURATIONS "Debug;Release"
        IMPORTED_LOCATION_DEBUG
            "${CPPAD_VENDOR_ROOT}/x64-Debug/lib/cppad_lib.lib"
        IMPORTED_LOCATION_RELEASE
            "${CPPAD_VENDOR_ROOT}/x64-Release/lib/cppad_lib.lib"
        INTERFACE_INCLUDE_DIRECTORIES
            "${CPPAD_VENDOR_ROOT}/x64-Release/include"
    )
else()
    include(FetchContent)
    FetchContent_Declare(
        cppad
        GIT_REPOSITORY https://github.com/coin-or/CppAD.git
        GIT_TAG        20240000.7
        GIT_SHALLOW    TRUE
    )
    # Download headers only — do NOT run CppAD's CMakeLists.txt.
    # CppAD's build system creates a custom target named "test" which
    # conflicts with CTest's reserved target when testing is enabled.
    # All AD usage in this project is header-only; cppad_lib is not needed.
    # CMP0169: suppress deprecation of FetchContent_Populate (still needed
    # to skip CppAD's own CMakeLists, which conflicts with CTest's "test" target).
    cmake_policy(SET CMP0169 OLD)
    FetchContent_GetProperties(cppad)
    if(NOT cppad_POPULATED)
        FetchContent_Populate(cppad)
    endif()

    # CppAD's cmake generates cppad/configure.hpp from configure.hpp.in.
    # Because we skip CppAD's CMakeLists (to avoid its conflicting "test"
    # custom target), we must synthesise configure.hpp ourselves.
    # Note: CppAD 20240000.x stores headers under include/cppad/ — the
    # include root is ${cppad_SOURCE_DIR}/include, not ${cppad_SOURCE_DIR}.
    set(_cppad_configure_hpp "${cppad_SOURCE_DIR}/include/cppad/configure.hpp")
    if(NOT EXISTS "${_cppad_configure_hpp}")
        message(STATUS "Generating CppAD configure.hpp for Linux/non-MSVC build")
        # Use the CXX compiler identity — this project declares LANGUAGES CXX
        # only, so CMAKE_C_COMPILER_ID is never populated.
        if(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang|AppleClang")
            set(_cppad_gnu_flags  1)
            set(_cppad_msvc_flags 0)
            set(_cppad_has_gettimeofday 1)
            set(_cppad_has_mkstemp 1)
            set(_cppad_has_tmpnam_s 0)
        else()
            set(_cppad_gnu_flags  0)
            set(_cppad_msvc_flags 1)
            set(_cppad_has_gettimeofday 0)
            set(_cppad_has_mkstemp 0)
            set(_cppad_has_tmpnam_s 1)
        endif()
        file(CONFIGURE
            OUTPUT "${_cppad_configure_hpp}"
            CONTENT
"# ifndef CPPAD_CONFIGURE_HPP
# define CPPAD_CONFIGURE_HPP
// Auto-generated by Aetherion cmake/Dependencies.cmake
// (replaces the file that CppAD's own cmake would generate)

# define CPPAD_LINK_FLAGS_HAS_M32 0
# define CPPAD_COMPILER_HAS_CONVERSION_WARN 0
# define CPPAD_DISABLE_SOME_MICROSOFT_COMPILER_WARNINGS 1
# if _MSC_VER
# pragma warning( disable : 4100 )
# pragma warning( disable : 4127 )
# pragma warning( disable : 4723 )
# endif
# undef CPPAD_DISABLE_SOME_MICROSOFT_COMPILER_WARNINGS
# define CPPAD_DEBUG_AND_RELEASE 1
# define CPPAD_USE_CPLUSPLUS_2011 1
# define CPPAD_USE_CPLUSPLUS_2017 0
# define CPPAD_PACKAGE_STRING \"cppad-20240000.7\"
# define CPPAD_HAS_ADOLC 0
# define CPPAD_HAS_COLPACK 0
# define CPPAD_HAS_EIGEN 0
# define CPPAD_HAS_IPOPT 0
# define CPPAD_DEPRECATED
# define CPPAD_BOOSTVECTOR 0
# define CPPAD_CPPADVECTOR 1
# define CPPAD_STDVECTOR 0
# define CPPAD_EIGENVECTOR 0
# define CPPAD_HAS_GETTIMEOFDAY @_cppad_has_gettimeofday@
# define CPPAD_TAPE_ADDR_TYPE unsigned int
# define CPPAD_IS_SAME_TAPE_ADDR_TYPE_SIZE_T 0
# define CPPAD_TAPE_ID_TYPE unsigned int
# ifndef CPPAD_MAX_NUM_THREADS
# define CPPAD_MAX_NUM_THREADS 48
# endif
# define CPPAD_HAS_MKSTEMP @_cppad_has_mkstemp@
# define CPPAD_HAS_TMPNAM_S @_cppad_has_tmpnam_s@
# define CPPAD_C_COMPILER_CMD \"${CMAKE_C_COMPILER}\"
# define CPPAD_C_COMPILER_GNU_FLAGS @_cppad_gnu_flags@
# define CPPAD_C_COMPILER_MSVC_FLAGS @_cppad_msvc_flags@
# define CPPAD_IS_SAME_UNSIGNED_INT_SIZE_T 0
# define CPPAD_PADDING_BLOCK_T
# define CPPAD_NULL     nullptr
# define CPPAD_NOEXCEPT noexcept
# ifdef NDEBUG
# define CPPAD_NDEBUG_NOEXCEPT noexcept
# else
# define CPPAD_NDEBUG_NOEXCEPT
# endif
# endif
"
            @ONLY
        )
    endif()

    add_library(cppad_headers INTERFACE)
    target_include_directories(cppad_headers INTERFACE ${cppad_SOURCE_DIR}/include)
    # Disable CppAD's NaN-checking feature: it calls CppAD::local::temp_file()
    # which is defined in cppad_lib (compiled). We use CppAD header-only, so
    # defining CPPAD_CHECK_FOR_NAN=0 removes the only cppad_lib dependency.
    target_compile_definitions(cppad_headers INTERFACE CPPAD_CHECK_FOR_NAN=0)
    add_library(CppAD::cppad ALIAS cppad_headers)
endif()

# ------------------------------------------------------------------------------
# Eigen3 (vendored headers)
# ------------------------------------------------------------------------------
set(EIGEN3_VENDOR_DIR "${CMAKE_SOURCE_DIR}/vendor/eigen")

if(EXISTS "${EIGEN3_VENDOR_DIR}/Eigen/Dense")
    message(STATUS "Using vendored Eigen headers in ${EIGEN3_VENDOR_DIR}")

    add_library(eigen3_vendor INTERFACE)
    target_include_directories(eigen3_vendor
        INTERFACE
            "${EIGEN3_VENDOR_DIR}"
    )

    add_library(Eigen3::Eigen ALIAS eigen3_vendor)
else()
    message(FATAL_ERROR
        "Eigen3 not found: vendored headers at "
        "${EIGEN3_VENDOR_DIR}/Eigen/Dense"
    )
endif()

# ------------------------------------------------------------------------------
# nlohmann/json (vendored header-only)
# ------------------------------------------------------------------------------
add_library(nlohmann_json INTERFACE)

target_include_directories(nlohmann_json
    INTERFACE
        ${CMAKE_CURRENT_SOURCE_DIR}/vendor
)

target_compile_definitions(nlohmann_json
    INTERFACE
        NLOHMANN_JSON_HEADER_ONLY
)
