name: Coverage

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  upload-coverage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt update && sudo apt install -y lcov gcc-13 g++-13

    - name: Configure compiler alternatives
      run: |
        sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-13 100
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-13 100
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-13 100

    - name: Configure (GCC Debug + coverage flags)
      run: cmake --preset=gcc-debug

    - name: Build
      run: cmake --build --preset=gcc-debug

    - name: Run tests
      run: ctest --preset=gcc-test

    - name: Capture coverage data
      run: |
        lcov --capture \
             --directory build/gcc-debug \
             --output-file build/gcc-debug/coverage.info \
             --gcov-tool gcov-13 \
             --base-directory .

    - name: Filter out tests and third-party code
      run: |
        lcov --remove build/gcc-debug/coverage.info \
             '*/tests/*' \
             '*/_deps/*' \
             '/usr/*' \
             --output-file build/gcc-debug/coverage_filtered.info

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: onurtuncer/Aetherion
        files: build/gcc-debug/coverage_filtered.info
