name: GCC Release Build

on:
  push:
    paths-ignore: ['README.md']
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y gcc-13 g++-13

      - name: Configure compiler alternatives
        run: |
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-13 100
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-13 100

      - name: Configure (GCC Release)
        run: cmake --preset=gcc-release

      - name: Build
        run: cmake --build --preset=gcc-release

      - name: Run tests
        run: ctest --preset=gcc-release
